### ISSUE TITLE
Can not login for some reason

### ISSUE THREAD

**Issue by chagai95** [devture/matrix-synapse-shared-secret-auth#11]
Dec 04 14:29:07 localhost.localdomain matrix-synapse[12295]: 2021-12-04 13:29:07,194 - shared_secret_authenticator - 41 - INFO - POST-2028 - Authenticating user: @me:chagai.website
Dec 04 14:29:07 localhost.localdomain matrix-synapse[12295]: 2021-12-04 13:29:07,195 - shared_secret_authenticator - 54 - INFO - POST-2028 - Bad hmac value for user: @me:chagai.website

**Comment by chagai95** [comment]
Just found an answer [here](https://matrix.to/#/!PukFFdIcHgtaaHZflT:devture.com/$16019124962783BFWej:devture.com?via=devture.com&via=matrix.org&via=chat.weho.st) so I'm gonna close this:

> Authentication then falls back to Synapse's regular authentication flow. That one probably succeeds.

**Comment by almightybob** [comment]
Could you share your findings? I'm having the same problem.
