### ISSUE TITLE
Synapse docker using Python 3.9

### ISSUE THREAD

**Issue by Wyrrrd** [devture/matrix-synapse-shared-secret-auth#17]
Since Version 1.54.0 Synapse uses Python 3.9 in its docker images by default.

This causes the Synapse server to fail starting, logging "Module not found" when using the mount path described in this projects installation instructions (needs to be `/usr/local/lib/python3.9/site-packages/shared_secret_authenticator.py`).

**Comment by spantaleev** [comment]
Thanks for the report! Fixed now
