### ISSUE TITLE
account_handler error after upgrade

### ISSUE THREAD

**Issue by ajkessel** [devture/matrix-synapse-shared-secret-auth#19]
I recently attempted to update from an older version of this module to the latest. matrix-synapse refuses to start with the following error:
`TypeError: SharedSecretAuthProvider.__init__() got an unexpected keyword argument 'account_handler' `
What am I doing wrong?

**Comment by spantaleev** [comment]
Have you read this? https://github.com/devture/matrix-synapse-shared-secret-auth/blob/master/CHANGELOG.md#version-2

**Comment by ajkessel** [comment]
OK, I see now. There were more changes in the configuration needed than I realized -- following all the examples there fixed my problems.
