### ISSUE TITLE
Availability for dendrite

### ISSUE THREAD

**Issue by traktuner** [devture/matrix-synapse-shared-secret-auth#23]
Hello,
is this also possible for dendrite?
The docker image for dendrite does not include python, so maybe there will be a native go version?
Thank you very much!

**Comment by ibeckermayer** [comment]
I'm also interested in this question. If not, I'd be interested in aiding in the development.

**Comment by traktuner** [comment]
Since most mautrix bridges now use the appservice method, that should be the way to go now:

**Comment by traktuner** [comment]
Since most mautrix bridges now use the appservice method, this should be the way to go now:
https://docs.mau.fi/bridges/general/double-puppeting.html#appservice-method-new

And therefore I am going to close this issue.
