### ISSUE TITLE
Store secret key as an actual secret in docker

### ISSUE THREAD

**Issue by zoomyboy** [devture/matrix-synapse-shared-secret-auth#24]
Hey people,

I am currently using the matrixdotorg/synapse docker image.

In order to modify the configuration file (homeserver.yaml), this needs to be mounted in the container as a volume. Also this file is readable by others but i'm pretty fine with it (until now) since this file is basically the default configuration that comes with the container - so it doesn't contain any sensitive data.

However, putting the shared secret directly into that file is probably dangerous. This also applies to my bridge configurations since the same setup roughly applies to them as well, so I also need to add that secret here - also readable for everyone.

Is there a safer way to store this via an environment variable and interpolate this on startup? That way I can store this into docker secrets, Kubernetes, gpg whatever ...

**Comment by spantaleev** [comment]
This is configured like any other Synapse module. The configuration needs to be stored in `homeserver.yaml` and passed to the module from there.

Theoretically, we can go our own way and start reading configuration from environment variables, Docker secrets, etc., but.. that's non-standard, requires additional work and is likely of little benefit.

-----

As you said, this applies to your bridge configuration too, so similar custom work may be needed there.

Perhaps you should look for a way to template `homeserver.yaml`, process secrets coming from elsewhere (perhaps via an init container) and feed the final result to Synapse.

**Comment by zoomyboy** [comment]
I'll try this out. Thanks.
