### ISSUE TITLE
FAQ doesn't explain why this isn't an evil backdoor (even though it's not)

### ISSUE THREAD

**Issue by jakecoble** [devture/matrix-synapse-shared-secret-auth#25]
The thing that makes this _not_ an evil backdoor is the fact that it's not circumventing end-to-end encryption. Logging into the user's account doesn't mean that the server is reading the user's encrypted messages. Element sends encrypted messages to unverified sessions by default, so it's possible to eavesdrop on conversations by logging into the user's account and creating device keys. But those would be visible as unverified sessions, and this module doesn't do that anyway. Is that all correct?

The FAQ as it stands isn't reassuring to someone who doesn't understand Matrix as much as you do. "data that they already host and own" is vague about _what_ data we're talking about, and "Your data is on my server so I can do what I want," isn't an argument – people rely on Matrix for private, secure communication, and subverting that expectation _would_ be evil.

**This module isn't an evil backdoor.** I just think that the current documentation could do a _much_ better job of explaining why that is by pointing out how it doesn't circumvent E2EE and generally can't do anything the user wouldn't notice (probably?).

**Comment by spantaleev** [comment]
Many of us are hosting our own Matrix server. Gaining a login session (as any user on the server) does not give us anything we can't already do by inspecting the database manually. Yes, E2EE would help and those messages cannot be read neither by inspecting the database, nor by getting a basic session with this module.

Many of us also don't use E2EE for various rooms, so gaining a login session is enough to see all messages in this rooms.

**Comment by jakecoble** [comment]
Yeah, and I think the FAQ should say that. "Gaining a login session (as any user on the server) does not give us anything we can't already do by inspecting the database manually," is clear and concise and I think should be the answer to [this](url) FAQ question.
