### ISSUE TITLE
make new release with setup.py included

### ISSUE THREAD

**Issue by L0ric0** [devture/matrix-synapse-shared-secret-auth#4]
i want to add an aur package for arch linux. but installing without a setup.py isn't nice. so it would be nice to have a release with the setup.py included so that the package isn't using master.

**Comment by spantaleev** [comment]
The 1.0.2 tagged release should be of help! Thanks for making an AUR package! :+1: 

We can update the installation instructions in the README to mention it.

**Comment by L0ric0** [comment]
If you want to update the README be my friend. In the aur there are now two packages for matrix-synapse-shared-secret-auth 
* [python-matrix-synapse-shared-secret-auth](https://aur.archlinux.org/packages/python-matrix-synapse-shared-secret-auth/)
* [python-matrix-synapse-shared-secret-auth-git](https://aur.archlinux.org/packages/python-matrix-synapse-shared-secret-auth-git/)

When you do a new release could you flag the python-matrix-synapse-shared-secret-auth as out-of-date, then i can update the package.

**Comment by spantaleev** [comment]
Thanks for creating these packages! :+1: 
I've mentioned them on the README. 

I'll try to remember to flag the AUR package out of date when making a new release!
