### ISSUE TITLE
Install on docker matrixdotorg/synapse

### ISSUE THREAD

**Issue by Ulrar** [devture/matrix-synapse-shared-secret-auth#9]
Hi,

I'm guessing not but is there a way to install this when using the official matrixdotorg/synapse docker image ?

Thanks

**Comment by spantaleev** [comment]
There is. Both [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) and [matrix-corporal](https://github.com/devture/matrix-corporal) make use of this module with the official `matrixdotorg/synapse` Docker image.

You need to mount this module's Python file (`shared_secret_authenticator.py`) into the image like this: https://github.com/devture/matrix-corporal/blob/597ef474d4019cf182bed71d94a8b2a047bf75ce/etc/services/docker-compose.yaml#L31

You then define the password provider in the `password_providers` configuration key in `homeserver.yaml` (if you're using v1 of this module) or in the `modules` configuration key. See our `CHANGELOG.md` file for a difference between versions.

Do note that if you're using v2, you may hit this problem with Element: https://github.com/vector-im/element-web/issues/19605

**Comment by Ulrar** [comment]
Ok I see, it just needs to be mounted in the container.
I've just setup v1 since I pretty much only use element.

Thanks !
